[package]
name = "mango"
description = "The Mango programming language (UNDER CONSTRUCTION)"
version = "0.2.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
homepage = "https://mangolang.org/"
license = "Apache-2.0"
publish = true
include = [
    "src/**/*",
    "Cargo.toml"
]

[dependencies]
regex = "0.2.*"
string-interner = "0.6.*"
lazy_static = "1.0.*"
derive-new = "0.5.*"
cargo-wasm = "0.4.*"

[profile.release]
lto = true

[lib]
name = "mango"
path = "src/lib.rs"

[[bin]]
name = "mango"
path = "src/mango/ui/cli/main.rs"

#[[bin]]
#name = "mango-webi"
#path = "src/mango/ui/webi/compile_str.rs"
