#!/usr/bin/env bash

# Make sure to fail if any check fails
set -e
set -o pipefail

# Get the hook utils directory
util_dir="$(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd))/hooks/utils"

# Check that a tag was created for this version
PYTHONPATH="$util_dir":$PYTHONPATH python3 "$util_dir/check_version_tag.py"
