
# Check that the code compiles. Also checks tests and style, but non-blocking.

name: 'Basic tests Mango CLI'

on:
  push:

jobs:
  checks:
    name: Compile and test (basic)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ci/pipeline/make/debug.sh
      - name: Test
        continue-on-error: true
        run: ci/pipeline/test/test.sh
      - name: Lint
        continue-on-error: true
        run: ci/pipeline/test/lint.sh
      - name: Style
        continue-on-error: true
        run: ci/pipeline/test/style.sh
      - name: Documentation
        continue-on-error: true
        run: ci/pipeline/make/docs.sh
