
name: 'Simplified checks for Mango CLI'

on:
  push:
  workflow_dispatch:

jobs:
  checks:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checks
        run: docker build -f ci/simple.Dockerfile .
